GET http://localhost:8000/elements

###

GET http://localhost:8000/elements/5e5e448b1c997d028833371d

###

GET http://localhost:8000/elements/by?name=Hydrogen

###

GET http://localhost:8000/elements/by?atomicNumber=1&atomicMass=1.00794

###

GET http://localhost:8000/elements/by?atomicMass=6.941&atomicMass=1.00794

###

PATCH http://localhost:8000/elements/5e5db551b794262d640b3650
Content-Type: application/json

{
    "atomicNumber": 1,
    "atomicMass": 1.0079,
    "symbol": "H",
    "name": "Hydrogen"
}

###

DELETE http://localhost:8000/elements/by?atomicNumber=2

###

DELETE http://localhost:8000/elements/by?name=Hydrogen

###

DELETE http://localhost:8000/elements/5e5e448b1c997d028833371d

###

POST http://localhost:8000/elements
Content-Type: application/json

{
    "atomicNumber": 1,
    "atomicMass": 1.0079,
    "symbol": "H",
    "name": "Hydrogen"
}


###

POST http://localhost:8000/elements
Content-Type: application/json

{
    "atomicNumber": 2,
    "atomicMass": 4.0026,
    "symbol": "He",
    "name": "Helium"
}

###

POST http://localhost:8000/elements
Content-Type: application/json

{
    "atomicNumber": 3,
    "atomicMass": 6.941,
    "symbol": "Li",
    "name": "Lithium"
}

###
