GET http://localhost:8000/elements

###

GET http://localhost:8000/elements/5e5feaa4c8e2252090b5171d

###

GET http://localhost:8000/elements/by?name=Hydrogen

###

GET http://localhost:8000/elements/by?atomicNumber=3

###

GET http://localhost:8000/elements/by?atomicMass=6.941&atomicMass=1.00794

###

PATCH http://localhost:8000/elements/5e5feaa4c8e2252090b5171d
Content-Type: application/json

{
    "atomicNumber": 1,
    "atomicMass": 1.007,
    "symbol": "H",
    "name": "Hydrogen"
}

###

DELETE http://localhost:8000/elements/by?atomicNumber=8

###

DELETE http://localhost:8000/elements/by?name=Lithium

###

DELETE http://localhost:8000/elements/5e604662c025d134608bb25d

###

POST http://localhost:8000/elements
Content-Type: application/json

{
    "atomicNumber": 1,
    "atomicMass": 1.007,
    "symbol": "H",
    "name": "Hydrogen"
}


###

POST http://localhost:8000/elements
Content-Type: application/json

{
    "atomicNumber": 2,
    "atomicMass": 4.0026,
    "symbol": "He",
    "name": "Helium"
}

###

POST http://localhost:8000/elements
Content-Type: application/json

{
    "atomicNumber": 3,
    "atomicMass": 6.941,
    "symbol": "Li",
    "name": "Lithium"
}

###
